### PR TITLE
Remove clearpins

### LINKED ISSUE #164: Random Pruner Performance HotSpot
# What

So in addition to memory, our CPU is pegged, and, moreover, given the way that GraphSync works, this is also likely the source of both SP bandwidth problems and memory usage. (if block putting and processing is very slow, graphsync will accumulate them in memory)

Profiling names a clear hotspot: the Random Pruner and specifically the inner loop in clearPins, which if I'm reading right runs on every block put.

Let's try to improve this to solve MANY problems.

Screen Shot 2023-01-17 at 12 33 55 PM

### PR DESCRIPTION
**Pull request by hannahhoward**
# Goals

fix #164 

# Implementation

Maybe I'm reading this code wrong but essentially:
- pins is a list of items not to delete.
- you only check this list in a prune
- instead of keeping it up to date on every block pin, just delete when you need check it.
- possible memory growth here but honestly, we're getting killed with block data cause of this and I think it'll help a lot.

### CODE REVIEW

**Comment by hannahhoward** [comment]
What's up with CI?

**Review by elijaharita — APPROVED** [review]
sure, looks good to me. hope it helps!

**Comment by rvagg** [comment]
CI looks broken this time because of azure ubuntu DNS issues by the look of it; 🤦 this is because of ffi of course.

**Comment by rvagg** [comment]
(I'm skeptical this is going to have much effect but it's worth a try and it's a good start)

**Pull request merged**
